name: price_memo
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.5
  firebase_analytics: ^9.0.4
  firebase_auth: ^3.3.4
  flutterfire_ui: ^0.3.0
  cloud_firestore: ^3.1.5
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  beamer: ^1.1.0
  cloud_firestore_odm: ^1.0.0-dev.5
  json_annotation: ^4.4.0
  flutter_hooks: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  cloud_firestore_odm_generator: ^1.0.0-dev.5
  json_serializable: ^6.1.3

flutter:

  uses-material-design: true
