name: price_memo
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.5
  firebase_analytics: ^9.0.4
  firebase_auth: ^3.3.4
  flutterfire_ui: ^0.3.0
  cloud_firestore: ^3.1.5
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  beamer: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
